apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
spec:
  destination:
    name: ''
    namespace: 'postgres-operator'
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/postgres-operator
    repoURL: 'https://opensource.zalando.com/postgres-operator'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator-ui
spec:
  destination:
    name: ''
    namespace: 'postgres-operator'
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/postgres-operator-ui
    repoURL: 'https://opensource.zalando.com/postgres-operator'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
