apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
spec:
  destination:
    name: ''
    namespace: 'monitoring'
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/tempo-distributed
    repoURL: 'https://github.com/grafana/helm-charts'
    targetRevision: HEAD
    helm:
      values: |
        tempo:
          storage:
            trace:
              backend: s3
              s3:
                endpoint: ams1.vultrobjects.com
                region: ams1
                accessKeyId: ${S3_ACCESS_KEY_ID}
                secretAccessKey: ${S3_SECRET_ACCESS_KEY}
                s3ForcePathStyle: false
                insecure: false
              wal:
                path: /var/tempo/wal
          extraArgs: ["-config.expand-env=true"]
          extraEnvFrom:
            - secretRef:
                name: tempo-s3
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
